services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rinha-api-1
      - rinha-api-2
    ports:
      - "9999:9999"
    networks:
      - rinha-api-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  rinha-api-1: &rinha-api
    # image: pewpeeo/rinha-backend-2025:tag
    build: .
    hostname: rinha-api-1
    container_name: rinha-api-1
    environment:
      - PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - NODE_ENV=production
    networks:
      - rinha-api-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.675"
          memory: "167.5MB"

  rinha-api-2:
    <<: *rinha-api
    hostname: rinha-api-2
    container_name: rinha-api-2
    environment:
      - PORT=8080
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - NODE_ENV=production

networks:
  rinha-api-network:
    driver: bridge
  payment-processor:
    external: true